//! Read-only system-information surface: what this
//! device IS, assembled in one read from the seams that already exist.
//!
//! The shape [`crate::network_state`], [`crate::time_status`] and
//! [`crate::storage_status`] take: a trait with an unavailable default so a
//! dry-run daemon or a test never inspects its host, a production observer
//! only `main.rs` attaches, and a pure rendering function the tests drive
//! with literal evidence. Served as `GetSystemInfo` on the bus and
//! `GET /api/v1/system/info` over HTTPS.
//!
//! **Nothing here is a second mechanism.** Every fact is read from where it
//! already lives and is never restated anywhere else.

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::time::UNIX_EPOCH;

use anyhow::Result;
use serde_json::{Value as Json, json};

use crate::deployment::Status;

/// The shipped bill of materials, relative to the observer's root.
pub const MANIFEST_PATH: &str = "usr/share/mica/manifest.tsv";
/// systemd's machine id, relative to the observer's root.
pub const MACHINE_ID_PATH: &str = "etc/machine-id";
/// The distribution identity file, relative to the observer's root.
pub const OS_RELEASE_PATH: &str = "etc/os-release";
/// The device-tree model string (arm boards), relative to the root.
pub const DT_MODEL_PATH: &str = "sys/firmware/devicetree/base/model";
/// DMI's product name (x64 boards), relative to the root.
pub const DMI_PRODUCT_PATH: &str = "sys/class/dmi/id/product_name";
/// DMI's board vendor (x64 boards), relative to the root.
pub const DMI_VENDOR_PATH: &str = "sys/class/dmi/id/board_vendor";
/// The kernel release (`uname -r`), relative to the root.
pub const KERNEL_RELEASE_PATH: &str = "proc/sys/kernel/osrelease";
/// The kernel version string (`uname -v`), relative to the root.
pub const KERNEL_VERSION_PATH: &str = "proc/sys/kernel/version";
/// Seconds since boot, relative to the root.
pub const UPTIME_PATH: &str = "proc/uptime";
/// The baked update configuration — the mandatory member of the `meta/` public
/// set, and therefore the evidence that this image was built by a pipeline
/// that provisions a trust anchor at all. Relative to the observer's root.
pub const BAKED_META_MANIFEST_PATH: &str = "usr/share/mica/meta/updates/manifest.json";
/// The development-grade marker, baked beside it exactly when the signing
/// material this image was built from was generated by
/// `pkgs/mica-boot/dev-keys.sh`. Relative to the observer's root.
pub const BAKED_META_MARKER_PATH: &str = "usr/share/mica/meta/GENERATED";
/// The key in the marker naming the domains the generator wrote.
pub const MARKER_DOMAINS_KEY: &str = "DOMAINS";

/// The most manifest rows the surface carries. A real image ships a few
/// hundred; the cap exists so a corrupted or hostile file cannot grow the
/// answer without bound, and crossing it is reported as `truncated`.
pub const MAX_MANIFEST_ROWS: usize = 4096;

/// The packages whose manifest row names the system (image) version, in
/// order of preference: the system metapackage where the image has one, and
/// the management daemon otherwise.
const SYSTEM_VERSION_PACKAGES: [&str; 2] = ["mica-system", "micad"];

/// One row of the manifest.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PackageRow {
    /// Debian package name.
    pub name: String,
    /// Debian version string.
    pub version: String,
    /// Debian architecture.
    pub architecture: String,
}

impl PackageRow {
    /// Whether this row is one of this repository's packages, by the rule
    /// `verify/src/checks-root.ts` applies: the name starts with `mica`.
    #[must_use]
    pub fn is_mica(&self) -> bool {
        self.name.starts_with("mica")
    }
}

/// The parsed manifest.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Manifest {
    /// The rows that parsed, in file order, at most [`MAX_MANIFEST_ROWS`].
    pub rows: Vec<PackageRow>,
    /// Rows that were not three tab-separated fields.
    pub malformed: usize,
    /// Whether rows beyond the cap were dropped.
    pub truncated: bool,
}

/// Parse the manifest text: `#` lines and blank lines are skipped, every
/// other line is three tab-separated fields or is counted malformed.
#[must_use]
pub fn parse_manifest(text: &str) -> Manifest {
    let mut manifest = Manifest::default();
    for line in text.lines() {
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<&str> = line.split('\t').collect();
        if fields.len() != 3 || fields.iter().any(|field| field.is_empty()) {
            manifest.malformed += 1;
            continue;
        }
        if manifest.rows.len() >= MAX_MANIFEST_ROWS {
            manifest.truncated = true;
            continue;
        }
        manifest.rows.push(PackageRow {
            name: fields[0].to_string(),
            version: fields[1].to_string(),
            architecture: fields[2].to_string(),
        });
    }
    manifest
}

/// Parse `os-release`: `KEY=value` lines, values optionally double- or
/// single-quoted, comments and blank lines skipped. No escape processing
/// beyond stripping the quotes, which is all the fields this surface reports
/// ever need.
#[must_use]
pub fn parse_os_release(text: &str) -> BTreeMap<String, String> {
    let mut fields = BTreeMap::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let value = value.trim();
        let value = value
            .strip_prefix('"')
            .and_then(|rest| rest.strip_suffix('"'))
            .or_else(|| {
                value
                    .strip_prefix('\'')
                    .and_then(|rest| rest.strip_suffix('\''))
            })
            .unwrap_or(value);
        fields.insert(key.trim().to_string(), value.to_string());
    }
    fields
}

/// Whether `text` is a machine id in the form systemd writes: 32 lowercase
/// hex characters.
#[must_use]
pub fn is_machine_id(text: &str) -> bool {
    text.len() == 32
        && text
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

/// Where the board model was read from.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Board {
    /// The model string, trimmed of the device tree's trailing NUL.
    pub model: String,
    /// `devicetree` or `dmi`.
    pub source: &'static str,
}

/// The grade of the signing material this image was built from.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TrustGrade {
    /// The marker is baked: the CA in this image's keyring, or the package
    /// signing key it trusts, or both, came out of a generator rather than a
    /// ceremony. `domains` is what the marker's `DOMAINS=` line names, so a
    /// mixed image says WHICH half.
    Development { domains: Vec<String> },
    /// The baked set is there and carries no marker: material an operator
    /// placed on purpose.
    Production,
}

/// Everything the observer reads. Each field is what one soft read produced;
/// absent means the read did not answer.
#[derive(Debug, Clone)]
pub struct SystemInfoEvidence {
    /// A well-formed machine id, or the reason there is none.
    pub machine_id: Result<String, String>,
    /// The board model, when the firmware exports one.
    pub board: Option<Board>,
    /// `uname -r`.
    pub kernel_release: Option<String>,
    /// `uname -v`.
    pub kernel_version: Option<String>,
    /// The parsed `os-release`, empty when the file is absent.
    pub os_release: BTreeMap<String, String>,
    /// The parsed manifest, or `None` when the file is absent.
    pub manifest: Option<Manifest>,
    /// The manifest file's mtime in seconds since the epoch: the pinned
    /// `SOURCE_DATE_EPOCH` every file in the image carries, not a build date.
    pub file_epoch: Option<u64>,
    /// Whole seconds since boot.
    pub uptime_seconds: Option<u64>,
    /// The grade of this image's signing material, or `None` when the baked
    /// `meta/` tree is not there to be asked. **`None` is not `Production`**:
    /// an image that provisions no anchor has no marker for the same reason a
    /// production image has none, and reporting the two the same way would
    /// have a device claiming a production CA it cannot see.
    pub trust: Option<TrustGrade>,
}

impl Default for SystemInfoEvidence {
    /// Nothing read yet: the machine id is absent with a reason, everything
    /// else is absent.
    fn default() -> Self {
        Self {
            machine_id: Err("not read".to_string()),
            board: None,
            kernel_release: None,
            kernel_version: None,
            os_release: BTreeMap::new(),
            manifest: None,
            file_epoch: None,
            uptime_seconds: None,
            trust: None,
        }
    }
}

/// This daemon's own identity, as its build embedded it — the values
/// `micad --version` prints, read from the same place.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DaemonIdentity {
    /// The daemon's name, `micad`: the executable, not the package.
    pub name: &'static str,
    /// The package version, `MICA_PACKAGE_VERSION`, or `unknown` for an
    /// unpackaged build.
    pub version: &'static str,
}

impl DaemonIdentity {
    /// The identity of this build.
    #[must_use]
    pub fn this_build() -> Self {
        Self {
            name: "micad",
            version: option_env!("MICA_PACKAGE_VERSION")
                .filter(|version| !version.trim().is_empty())
                .unwrap_or("unknown"),
        }
    }
}

/// Read-only source of system-information evidence.
#[async_trait::async_trait]
pub trait SystemInfoSource: Send + Sync {
    /// Observe the current evidence.
    ///
    /// # Errors
    ///
    /// Returns an error only when this daemon has no observer at all; a
    /// production observer answers with absent evidence instead.
    async fn observe(&self) -> Result<SystemInfoEvidence>;
}

/// The observer a daemon without host access has: none.
pub struct UnavailableSystemInfo;

#[async_trait::async_trait]
impl SystemInfoSource for UnavailableSystemInfo {
    async fn observe(&self) -> Result<SystemInfoEvidence> {
        Err(anyhow::anyhow!(
            "this daemon observes no system information"
        ))
    }
}

/// Production observer over a filesystem root.
///
/// `root` is a path prefix rather than a hard-coded `/` so the whole read can
/// be driven over a fixture tree in a unit test; production is the same thing
/// rooted at `/`.
pub struct HostSystemInfo {
    root: PathBuf,
}

impl HostSystemInfo {
    /// The observer `main.rs` attaches on a device.
    #[must_use]
    pub fn production() -> Self {
        Self::at("/")
    }

    /// An observer rooted at `root`.
    #[must_use]
    pub fn at(root: impl Into<PathBuf>) -> Self {
        Self { root: root.into() }
    }

    fn path(&self, relative: &str) -> PathBuf {
        self.root.join(relative)
    }

    fn read_trimmed(&self, relative: &str) -> Option<String> {
        let bytes = std::fs::read(self.path(relative)).ok()?;
        // The device tree's model string is NUL-terminated; everything else
        // is a text file with a trailing newline. Both are trimmed the same
        // way.
        let text = String::from_utf8_lossy(&bytes);
        let text = text.trim_matches(|c: char| c == '\0' || c.is_whitespace());
        (!text.is_empty()).then(|| text.to_string())
    }

    fn machine_id(&self) -> Result<String, String> {
        let path = self.path(MACHINE_ID_PATH);
        match std::fs::read_to_string(&path) {
            Ok(text) => {
                let text = text.trim();
                if is_machine_id(text) {
                    Ok(text.to_string())
                } else {
                    Err(format!(
                        "/{MACHINE_ID_PATH} is not a 32-character lowercase hex machine id"
                    ))
                }
            }
            Err(err) => Err(format!("/{MACHINE_ID_PATH} is not readable: {err}")),
        }
    }

    fn board(&self) -> Option<Board> {
        if let Some(model) = self.read_trimmed(DT_MODEL_PATH) {
            return Some(Board {
                model,
                source: "devicetree",
            });
        }
        let product = self.read_trimmed(DMI_PRODUCT_PATH)?;
        let model = match self.read_trimmed(DMI_VENDOR_PATH) {
            Some(vendor) => format!("{vendor} {product}"),
            None => product,
        };
        Some(Board {
            model,
            source: "dmi",
        })
    }

    fn manifest(&self) -> (Option<Manifest>, Option<u64>) {
        let path = self.path(MANIFEST_PATH);
        let Ok(text) = std::fs::read_to_string(&path) else {
            return (None, None);
        };
        let epoch = std::fs::metadata(&path)
            .and_then(|meta| meta.modified())
            .ok()
            .and_then(|modified| modified.duration_since(UNIX_EPOCH).ok())
            .map(|since| since.as_secs());
        (Some(parse_manifest(&text)), epoch)
    }

    /// The grade of the signing material this image was built from.
    fn trust(&self) -> Option<TrustGrade> {
        if !self.path(BAKED_META_MANIFEST_PATH).is_file() {
            return None;
        }
        let marker = self.path(BAKED_META_MARKER_PATH);
        if !marker.exists() {
            return Some(TrustGrade::Production);
        }
        // Present and unreadable still reports Development, with no domains.
        // The marker's presence is the claim; its contents only say which
        // half, and a read that failed must not promote the image to
        // production for want of a domain list.
        let text = std::fs::read_to_string(&marker).unwrap_or_default();
        Some(TrustGrade::Development {
            domains: marker_domains(&text),
        })
    }

    fn uptime_seconds(&self) -> Option<u64> {
        let contents = std::fs::read_to_string(self.path(UPTIME_PATH)).ok()?;
        let secs: f64 = contents.split_whitespace().next()?.parse().ok()?;
        (secs.is_finite() && secs >= 0.0).then_some(secs as u64)
    }
}

#[async_trait::async_trait]
impl SystemInfoSource for HostSystemInfo {
    async fn observe(&self) -> Result<SystemInfoEvidence> {
        let (manifest, file_epoch) = self.manifest();
        Ok(SystemInfoEvidence {
            machine_id: self.machine_id(),
            board: self.board(),
            kernel_release: self.read_trimmed(KERNEL_RELEASE_PATH),
            kernel_version: self.read_trimmed(KERNEL_VERSION_PATH),
            os_release: std::fs::read_to_string(self.path(OS_RELEASE_PATH))
                .map(|text| parse_os_release(&text))
                .unwrap_or_default(),
            manifest,
            file_epoch,
            uptime_seconds: self.uptime_seconds(),
            trust: self.trust(),
        })
    }
}

/// Report a single current-domain declaration. An unreadable or malformed
/// declaration leaves the image development-grade without inferred domains.
fn marker_domains(text: &str) -> Vec<String> {
    let prefix = format!("{MARKER_DOMAINS_KEY}=");
    let mut declarations = text.lines().filter_map(|line| line.strip_prefix(&prefix));
    let Some(value) = declarations.next() else {
        return Vec::new();
    };
    if declarations.next().is_some() {
        return Vec::new();
    }
    let domains: Vec<_> = value.split_whitespace().collect();
    if domains
        .iter()
        .any(|domain| !matches!(*domain, "boot" | "verity" | "updates"))
        || domains
            .iter()
            .enumerate()
            .any(|(index, domain)| domains[..index].contains(domain))
    {
        return Vec::new();
    }
    domains.into_iter().map(str::to_string).collect()
}

/// `{"available": false, "detail": detail}` — the one spelling of absence.
fn absent(detail: impl Into<String>) -> Json {
    json!({ "available": false, "detail": detail.into() })
}

/// RFC 3339 for `epoch`, or `None` when it is out of range.
fn rfc3339(epoch: u64) -> Option<String> {
    let secs = i64::try_from(epoch).ok()?;
    chrono::DateTime::<chrono::Utc>::from_timestamp(secs, 0)
        .map(|when| when.to_rfc3339_opts(chrono::SecondsFormat::Secs, true))
}

/// `evidence` rendered as the JSON the bus method serves.
///
/// Every member is an object carrying `available`, so a consumer reads one
/// shape whether the fact is there or not, and an absent fact carries the
/// reason it is absent.
#[must_use]
pub fn info_json(
    evidence: &SystemInfoEvidence,
    deployment: Option<&Status>,
    daemon: &DaemonIdentity,
) -> Json {
    let machine_id = match &evidence.machine_id {
        Ok(id) => json!({ "available": true, "id": id }),
        Err(detail) => absent(detail.clone()),
    };
    let board = match &evidence.board {
        Some(board) => json!({ "available": true, "model": board.model, "source": board.source }),
        None => absent("no device-tree model and no DMI product name is exported by this board"),
    };
    let kernel = match (&evidence.kernel_release, &evidence.kernel_version) {
        (None, None) => absent(format!("/{KERNEL_RELEASE_PATH} is not readable")),
        (release, version) => json!({
            "available": true,
            "release": release,
            "version": version,
        }),
    };
    let release = if evidence.os_release.is_empty() {
        absent(format!("/{OS_RELEASE_PATH} is absent or empty"))
    } else {
        let mut root = serde_json::Map::new();
        root.insert("available".to_string(), json!(true));
        for (key, member) in [
            ("NAME", "name"),
            ("ID", "id"),
            ("VERSION", "version"),
            ("VERSION_ID", "versionId"),
            ("PRETTY_NAME", "prettyName"),
            ("BUILD_ID", "buildId"),
            ("IMAGE_ID", "imageId"),
            ("IMAGE_VERSION", "imageVersion"),
        ] {
            if let Some(value) = evidence.os_release.get(key) {
                root.insert(member.to_string(), json!(value));
            }
        }
        Json::Object(root)
    };
    let (system, packages) = match &evidence.manifest {
        None => (
            absent(format!(
                "/{MANIFEST_PATH} is absent; this root was not packed by the image pipeline"
            )),
            absent(format!("/{MANIFEST_PATH} is absent")),
        ),
        Some(manifest) => (
            system_json(manifest, evidence.file_epoch),
            packages_json(manifest),
        ),
    };
    let deployment = match deployment
        .and_then(|status| status.booted().map(|booted| (status, booted)))
    {
        None => absent("the native deployment backend did not report a running deployment"),
        Some((status, booted)) => json!({"available":true,"id":booted.id,"version":booted.version,
            "generation":booted.generation,"kernelId":booted.kernel_id,"kernelRelease":booted.kernel_release,
            "rootfsId":booted.rootfs_id,"confirmed":status.state.current.as_ref() == Some(&booted.id),
            "contentVerified":status.boot.content_verified,"secureBoot":status.boot.secure_boot,
            "backend":status.boot.backend,"bootVerified":status.boot.boot_verified}),
    };
    let uptime = match evidence.uptime_seconds {
        Some(seconds) => json!({ "available": true, "seconds": seconds }),
        None => absent(format!("/{UPTIME_PATH} is not readable")),
    };
    let trust = match &evidence.trust {
        None => absent(format!(
            "/{BAKED_META_MANIFEST_PATH} is absent, so this image provisions no trust anchor \
             and the grade of the material it was built from cannot be read off it -- which is \
             not the same as production"
        )),
        Some(TrustGrade::Production) => json!({ "available": true, "grade": "production" }),
        Some(TrustGrade::Development { domains }) => json!({
            "available": true,
            "grade": "development",
            "developmentDomains": domains,
            "marker": format!("/{BAKED_META_MARKER_PATH}"),
        }),
    };
    json!({
        "machineId": machine_id,
        "board": board,
        "kernel": kernel,
        "release": release,
        "system": system,
        "trust": trust,
        "daemon": {
            "name": daemon.name,
            "version": daemon.version,
        },
        "packages": packages,
        "deployment": deployment,
        "uptime": uptime,
    })
}

/// The `system` member: the image version by way of the system package's
/// manifest row, and the pinned file epoch the root carries.
fn system_json(manifest: &Manifest, file_epoch: Option<u64>) -> Json {
    let version_row = SYSTEM_VERSION_PACKAGES
        .iter()
        .find_map(|name| manifest.rows.iter().find(|row| row.name == *name));
    let mut root = serde_json::Map::new();
    match version_row {
        Some(row) => {
            root.insert("available".to_string(), json!(true));
            root.insert("version".to_string(), json!(row.version));
            root.insert("package".to_string(), json!(row.name));
        }
        None => {
            root.insert("available".to_string(), json!(false));
            root.insert(
                "detail".to_string(),
                json!(format!(
                    "no {} row in the manifest",
                    SYSTEM_VERSION_PACKAGES.join(" or ")
                )),
            );
        }
    }
    root.insert("fileEpoch".to_string(), file_epoch_json(file_epoch));
    Json::Object(root)
}

/// The `system.fileEpoch` member: the mtime every file in this root carries.
fn file_epoch_json(file_epoch: Option<u64>) -> Json {
    let Some(epoch) = file_epoch else {
        return absent(format!(
            "/{MANIFEST_PATH} has no readable mtime, so the epoch every file in this root was \
             pinned to cannot be read back from it"
        ));
    };
    let mut node = serde_json::Map::new();
    node.insert("available".to_string(), json!(true));
    node.insert("epoch".to_string(), json!(epoch));
    if let Some(date) = rfc3339(epoch) {
        node.insert("date".to_string(), json!(date));
    }
    Json::Object(node)
}

/// The `packages` member: every manifest row, with the mica ones marked.
fn packages_json(manifest: &Manifest) -> Json {
    let entries: Vec<Json> = manifest
        .rows
        .iter()
        .map(|row| {
            json!({
                "name": row.name,
                "version": row.version,
                "architecture": row.architecture,
                "mica": row.is_mica(),
            })
        })
        .collect();
    json!({
        "available": true,
        "count": manifest.rows.len(),
        "micaCount": manifest.rows.iter().filter(|row| row.is_mica()).count(),
        "malformedRows": manifest.malformed,
        "truncated": manifest.truncated,
        "entries": entries,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    const MANIFEST: &str = "#package\tversion\tarchitecture\n\
        base-files\t13.8\tarm64\n\
        mica-apid\t0.1.1-1\tarm64\n\
        mica-deploy\t0.1.1-1\tarm64\n\
        micad\t0.1.1-1\tarm64\n\
        systemd\t257.7-1\tarm64\n";

    fn daemon() -> DaemonIdentity {
        DaemonIdentity {
            name: "micad",
            version: "0.1.1-1",
        }
    }

    /// A fixture tree carrying every seam, so the assembly — the part where
    /// this module's bugs would live — runs end to end without a device.
    fn fixture_root() -> tempfile::TempDir {
        let dir = tempfile::tempdir().expect("tempdir");
        let root = dir.path();
        let write = |relative: &str, contents: &[u8]| {
            let path = root.join(relative);
            std::fs::create_dir_all(path.parent().expect("parent")).expect("mkdir");
            std::fs::write(path, contents).expect("write fixture");
        };
        write(MACHINE_ID_PATH, b"0123456789abcdef0123456789abcdef\n");
        write(MANIFEST_PATH, MANIFEST.as_bytes());
        write(
            OS_RELEASE_PATH,
            b"PRETTY_NAME=\"Debian GNU/Linux 13 (trixie)\"\nNAME=\"Debian GNU/Linux\"\nVERSION_ID=\"13\"\nID=debian\n# a comment\n",
        );
        write(DT_MODEL_PATH, b"Vendor CX3576 Board\0");
        write(KERNEL_RELEASE_PATH, b"6.1.115-mica\n");
        write(
            KERNEL_VERSION_PATH,
            b"#1 SMP PREEMPT Mon Sep 1 00:00:00 UTC 2026\n",
        );
        write(UPTIME_PATH, b"12345.67 8888.00\n");
        // PRODUCTION-shaped: the baked public set's required member is there
        // and no marker is beside it, because that is the released state. A
        // test that wants the development branch writes the marker itself.
        write(
            BAKED_META_MANIFEST_PATH,
            b"{ \"schema\": \"mica/meta/v1\", \"update\": { \"source\": null } }\n",
        );
        dir
    }

    #[test]
    fn the_manifest_parses_by_the_shipped_shape() {
        let manifest = parse_manifest(MANIFEST);
        assert_eq!(manifest.rows.len(), 5);
        assert_eq!(manifest.malformed, 0);
        assert!(!manifest.truncated);
        assert_eq!(manifest.rows[1].name, "mica-apid");
        assert_eq!(manifest.rows[1].version, "0.1.1-1");
        assert_eq!(manifest.rows[1].architecture, "arm64");
        assert!(manifest.rows[1].is_mica());
        assert!(!manifest.rows[0].is_mica());
    }

    /// A row that is not three fields is counted, not silently dropped and
    /// not allowed to poison the rows around it.
    #[test]
    fn a_malformed_row_is_counted_and_skipped() {
        let manifest = parse_manifest("a\t1\n\nb\t2\tamd64\tx\nc\t3\tamd64\n#h\n\t\t\n");
        assert_eq!(manifest.rows.len(), 1);
        assert_eq!(manifest.rows[0].name, "c");
        assert_eq!(manifest.malformed, 3);
    }

    /// The cap is enforced, and crossing it is reported rather than hidden.
    #[test]
    fn rows_beyond_the_cap_are_dropped_and_flagged() {
        let text: String = (0..(MAX_MANIFEST_ROWS + 5))
            .map(|i| format!("p{i}\t1\tamd64\n"))
            .collect();
        let manifest = parse_manifest(&text);
        assert_eq!(manifest.rows.len(), MAX_MANIFEST_ROWS);
        assert!(manifest.truncated);
    }

    #[test]
    fn os_release_values_lose_their_quotes() {
        let fields = parse_os_release("A=\"x y\"\nB='z'\nC=plain\n# c\n\nD\n");
        assert_eq!(fields["A"], "x y");
        assert_eq!(fields["B"], "z");
        assert_eq!(fields["C"], "plain");
        assert!(!fields.contains_key("D"));
    }

    #[test]
    fn a_machine_id_is_thirty_two_lowercase_hex() {
        assert!(is_machine_id("0123456789abcdef0123456789abcdef"));
        assert!(!is_machine_id("0123456789ABCDEF0123456789abcdef"));
        assert!(!is_machine_id("0123456789abcdef0123456789abcde"));
        assert!(!is_machine_id(""));
    }

    /// The assembly over a full fixture tree: every seam read from where it
    /// lives, and the pinned file epoch read from the manifest's mtime.
    #[tokio::test]
    async fn a_full_root_yields_every_member_available() {
        let root = fixture_root();
        let evidence = HostSystemInfo::at(root.path())
            .observe()
            .await
            .expect("observe");
        let deployment = Status::parse(&crate::deployment::tests::fixture().to_string()).unwrap();
        let info = info_json(&evidence, Some(&deployment), &daemon());

        assert_eq!(info["machineId"]["available"], true);
        assert_eq!(info["machineId"]["id"], "0123456789abcdef0123456789abcdef");
        assert_eq!(info["board"]["model"], "Vendor CX3576 Board");
        assert_eq!(info["board"]["source"], "devicetree");
        assert_eq!(info["kernel"]["release"], "6.1.115-mica");
        assert!(
            info["kernel"]["version"]
                .as_str()
                .is_some_and(|v| v.starts_with("#1 SMP"))
        );
        assert_eq!(info["release"]["id"], "debian");
        assert_eq!(
            info["release"]["prettyName"],
            "Debian GNU/Linux 13 (trixie)"
        );
        assert_eq!(info["release"]["versionId"], "13");
        assert_eq!(info["system"]["available"], true);
        assert_eq!(info["system"]["package"], "micad");
        assert_eq!(info["system"]["version"], "0.1.1-1");
        assert!(info["system"]["gitStamp"].is_null());
        assert!(info["system"]["commitDate"].is_null());
        // The file epoch is the manifest's mtime, which the fixture wrote just
        // now: a real epoch, rendered RFC 3339 beside it. On a composed image
        // it is the pinned SOURCE_DATE_EPOCH instead.
        let epoch = info["system"]["fileEpoch"]["epoch"]
            .as_u64()
            .expect("file epoch");
        assert!(epoch > 1_700_000_000, "epoch {epoch}");
        assert!(
            info["system"]["fileEpoch"]["date"]
                .as_str()
                .is_some_and(|d| d.ends_with('Z')),
            "{}",
            info["system"]
        );
        assert_eq!(info["daemon"]["name"], "micad");
        assert_eq!(info["daemon"]["version"], "0.1.1-1");
        assert!(info["daemon"]["commit"].is_null());
        assert_eq!(info["packages"]["count"], 5);
        assert_eq!(info["packages"]["micaCount"], 3);
        assert_eq!(info["packages"]["entries"][3]["name"], "micad");
        assert_eq!(info["packages"]["entries"][3]["mica"], true);
        assert_eq!(info["deployment"]["id"], "a".repeat(64));
        assert_eq!(info["deployment"]["kernelId"], "c".repeat(64));
        assert_eq!(info["deployment"]["rootfsId"], "d".repeat(64));
        assert_eq!(info["uptime"]["seconds"], 12345);
    }

    /// The empty root: every member is present and says WHY it is absent.
    /// Nothing is manufactured, and nothing panics.
    #[tokio::test]
    async fn an_empty_root_reports_every_member_absent_with_a_reason() {
        let dir = tempfile::tempdir().expect("tempdir");
        let evidence = HostSystemInfo::at(dir.path())
            .observe()
            .await
            .expect("observe");
        let info = info_json(&evidence, None, &daemon());
        for member in [
            "machineId",
            "board",
            "kernel",
            "release",
            "system",
            "packages",
            "deployment",
            "uptime",
        ] {
            assert_eq!(
                info[member]["available"], false,
                "{member}: {}",
                info[member]
            );
            assert!(
                info[member]["detail"]
                    .as_str()
                    .is_some_and(|d| !d.is_empty()),
                "{member} carries no reason: {}",
                info[member]
            );
        }
        // The daemon's own identity needs no file and is always there.
        assert_eq!(info["daemon"]["version"], "0.1.1-1");
    }

    /// A machine id that is not the systemd shape is absent evidence, not a
    /// value that looks like one.
    #[tokio::test]
    async fn a_malformed_machine_id_is_absent_with_the_reason() {
        let root = fixture_root();
        std::fs::write(root.path().join(MACHINE_ID_PATH), "not-an-id\n").expect("write");
        let evidence = HostSystemInfo::at(root.path())
            .observe()
            .await
            .expect("observe");
        let info = info_json(&evidence, None, &daemon());
        assert_eq!(info["machineId"]["available"], false);
        assert!(
            info["machineId"]["detail"]
                .as_str()
                .is_some_and(|d| d.contains("32-character")),
            "{}",
            info["machineId"]
        );
    }

    /// x64 has no device tree: the board comes from DMI, vendor first.
    #[tokio::test]
    async fn a_dmi_board_is_read_when_there_is_no_device_tree() {
        let root = fixture_root();
        std::fs::remove_file(root.path().join(DT_MODEL_PATH)).expect("drop dt model");
        let write = |relative: &str, contents: &str| {
            let path = root.path().join(relative);
            std::fs::create_dir_all(path.parent().expect("parent")).expect("mkdir");
            std::fs::write(path, contents).expect("write");
        };
        write(DMI_PRODUCT_PATH, "NUC13ANHi5\n");
        write(DMI_VENDOR_PATH, "Intel Corporation\n");
        let evidence = HostSystemInfo::at(root.path())
            .observe()
            .await
            .expect("observe");
        let info = info_json(&evidence, None, &daemon());
        assert_eq!(info["board"]["model"], "Intel Corporation NUC13ANHi5");
        assert_eq!(info["board"]["source"], "dmi");
    }

    /// The unavailable default refuses rather than inspecting the host.
    #[tokio::test]
    async fn the_unavailable_source_is_an_error() {
        assert!(UnavailableSystemInfo.observe().await.is_err());
    }

    /// The released state: the baked set is there and no marker is beside it.
    #[tokio::test]
    async fn a_root_with_no_marker_beside_its_baked_manifest_is_production() {
        let root = fixture_root();
        let evidence = HostSystemInfo::at(root.path())
            .observe()
            .await
            .expect("observe");
        assert_eq!(evidence.trust, Some(TrustGrade::Production));
        let info = info_json(&evidence, None, &daemon());
        assert_eq!(info["trust"]["available"], true);
        assert_eq!(info["trust"]["grade"], "production");
        // No marker path and no domain list on a production image: they are
        // facts about a marker, and there is none.
        assert!(info["trust"]["marker"].is_null());
        assert!(info["trust"]["developmentDomains"].is_null());
    }

    /// The marker is baked, so the device says so — and names WHICH half,
    /// because the mixed tree is real: a content signing ceremony's output
    /// copied in while the package signing key is still development-grade.
    #[tokio::test]
    async fn a_baked_marker_reports_development_and_the_domains_it_names() {
        let root = fixture_root();
        std::fs::write(
            root.path().join(BAKED_META_MARKER_PATH),
            "DEVELOPMENT-GRADE\nDOMAINS=boot verity updates\n",
        )
        .expect("write");
        let evidence = HostSystemInfo::at(root.path())
            .observe()
            .await
            .expect("observe");
        assert_eq!(
            evidence.trust,
            Some(TrustGrade::Development {
                domains: vec![
                    "boot".to_string(),
                    "verity".to_string(),
                    "updates".to_string()
                ],
            })
        );
        let info = info_json(&evidence, None, &daemon());
        assert_eq!(info["trust"]["grade"], "development");
        assert_eq!(info["trust"]["developmentDomains"][2], "updates");
        assert_eq!(
            info["trust"]["marker"],
            format!("/{BAKED_META_MARKER_PATH}")
        );
    }

    /// **The vacuity case, and the one this member exists to get right.** No
    /// baked `meta/` tree at all — an image built before the seam, or one
    /// whose staging broke — has no marker for the same reason a production
    /// image has none. Reporting it as production would have the surface
    /// claim a production CA on a device that provisions no anchor, so it is
    /// reported ABSENT with the reason.
    #[tokio::test]
    async fn a_root_with_no_baked_meta_at_all_is_absent_and_never_production() {
        let root = fixture_root();
        std::fs::remove_file(root.path().join(BAKED_META_MANIFEST_PATH)).expect("rm");
        let evidence = HostSystemInfo::at(root.path())
            .observe()
            .await
            .expect("observe");
        assert_eq!(evidence.trust, None);
        let info = info_json(&evidence, None, &daemon());
        assert_eq!(info["trust"]["available"], false);
        assert_ne!(info["trust"]["grade"], "production");
        assert!(
            info["trust"]["detail"]
                .as_str()
                .is_some_and(|d| d.contains(BAKED_META_MANIFEST_PATH)),
            "{}",
            info["trust"]
        );
    }

    /// A marker with no `DOMAINS=` line is still a marker. The presence is the
    /// claim; the line only says which half.
    #[test]
    fn a_marker_naming_no_domain_is_still_development() {
        assert_eq!(marker_domains("no domains here\n"), Vec::<String>::new());
        assert_eq!(marker_domains("DOMAINS=unknown\n"), Vec::<String>::new());
        assert_eq!(marker_domains("DOMAINS=boot boot\n"), Vec::<String>::new());
        // A duplicate assignment is not an alternate key-generation format.
        assert_eq!(
            marker_domains("DOMAINS=boot\nDOMAINS=boot verity updates\n"),
            Vec::<String>::new()
        );
    }
}
