//! Read-only system-information surface: what this
//! device IS, assembled in one read from the seams that already exist.
//!
//! The shape [`crate::network_state`], [`crate::time_status`] and
//! [`crate::storage_status`] take: a trait with an unavailable default so a
//! dry-run daemon or a test never inspects its host, a production observer
//! only `main.rs` attaches, and a pure rendering function the tests drive
//! with literal evidence. Served as `GetSystemInfo` on the bus and
//! `GET /api/v1/system/info` over HTTPS.
//!
//! **Nothing here is a second mechanism.** Every fact is read from where it
//! already lives and is never restated anywhere else.

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::time::UNIX_EPOCH;

use anyhow::Result;

mod json;
pub use json::*;

/// The shipped bill of materials, relative to the observer's root.
pub const MANIFEST_PATH: &str = "usr/share/mica/manifest.tsv";

/// The running deployment's signed descriptor, as the runkit hands it over.
/// Its core components are packages the root's manifest does not list: they
/// are composed over the root at boot.
pub const RUNNING_DEPLOYMENT_PATH: &str = "run/mica/deployment.json";
/// systemd's machine id, relative to the observer's root.
pub const MACHINE_ID_PATH: &str = "etc/machine-id";
/// The distribution identity file, relative to the observer's root.
pub const OS_RELEASE_PATH: &str = "etc/os-release";
/// The device-tree model string (arm boards), relative to the root.
pub const DT_MODEL_PATH: &str = "sys/firmware/devicetree/base/model";
/// DMI's product name (x64 boards), relative to the root.
pub const DMI_PRODUCT_PATH: &str = "sys/class/dmi/id/product_name";
/// DMI's board vendor (x64 boards), relative to the root.
pub const DMI_VENDOR_PATH: &str = "sys/class/dmi/id/board_vendor";
/// The kernel release (`uname -r`), relative to the root.
pub const KERNEL_RELEASE_PATH: &str = "proc/sys/kernel/osrelease";
/// The kernel version string (`uname -v`), relative to the root.
pub const KERNEL_VERSION_PATH: &str = "proc/sys/kernel/version";
/// Seconds since boot, relative to the root.
pub const UPTIME_PATH: &str = "proc/uptime";
/// The baked update configuration — the mandatory member of the `meta/` public
/// set, and therefore the evidence that this image was built by a pipeline
/// that provisions a trust anchor at all. Relative to the observer's root.
pub const BAKED_META_MANIFEST_PATH: &str = "usr/share/mica/meta/updates/manifest.json";
/// The development-grade marker, baked beside it exactly when the signing
/// material this image was built from was generated by
/// `pkgs/mica-boot/dev-keys.sh`. Relative to the observer's root.
pub const BAKED_META_MARKER_PATH: &str = "usr/share/mica/meta/GENERATED";
/// The key in the marker naming the domains the generator wrote.
pub const MARKER_DOMAINS_KEY: &str = "DOMAINS";

/// The most manifest rows the surface carries. A real image ships a few
/// hundred; the cap exists so a corrupted or hostile file cannot grow the
/// answer without bound, and crossing it is reported as `truncated`.
pub const MAX_MANIFEST_ROWS: usize = 4096;

/// The packages whose manifest row names the system (image) version, in
/// order of preference: the system metapackage where the image has one, and
/// the management daemon otherwise.
const SYSTEM_VERSION_PACKAGES: [&str; 2] = ["mica-system", "micad"];

/// One row of the manifest.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PackageRow {
    /// Debian package name.
    pub name: String,
    /// Debian version string.
    pub version: String,
    /// Debian architecture.
    pub architecture: String,
}

impl PackageRow {
    /// Whether this row is one of this repository's packages, by the rule
    /// `verify/src/checks-root.ts` applies: the name starts with `mica`.
    #[must_use]
    pub fn is_mica(&self) -> bool {
        self.name.starts_with("mica")
    }
}

/// The parsed manifest.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Manifest {
    /// The rows that parsed, in file order, at most [`MAX_MANIFEST_ROWS`].
    pub rows: Vec<PackageRow>,
    /// Rows that were not three tab-separated fields.
    pub malformed: usize,
    /// Whether rows beyond the cap were dropped.
    pub truncated: bool,
}

/// The core components of the running deployment's descriptor, as manifest
/// rows: package, version, architecture. The descriptor was verified by the
/// runkit before it was handed over; this only reads it, and anything that is
/// not a descriptor with core components gives no row.
#[must_use]
pub fn core_rows(envelope: &str) -> Vec<PackageRow> {
    use base64::Engine;
    let payload = serde_json::from_str::<serde_json::Value>(envelope)
        .ok()
        .and_then(|e| e.get("payload")?.as_str().map(str::to_owned))
        .and_then(|p| base64::engine::general_purpose::STANDARD.decode(p).ok())
        .and_then(|bytes| serde_json::from_slice::<serde_json::Value>(&bytes).ok());
    let Some(descriptor) = payload else {
        return Vec::new();
    };
    descriptor
        .get("core")
        .and_then(serde_json::Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(|core| {
            Some(PackageRow {
                name: core.get("package")?.as_str()?.to_owned(),
                version: core.get("version")?.as_str()?.to_owned(),
                architecture: core.get("arch")?.as_str()?.to_owned(),
            })
        })
        .collect()
}

/// Parse the manifest text: `#` lines and blank lines are skipped, every
/// other line is three tab-separated fields or is counted malformed.
#[must_use]
pub fn parse_manifest(text: &str) -> Manifest {
    let mut manifest = Manifest::default();
    for line in text.lines() {
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields: Vec<&str> = line.split('\t').collect();
        if fields.len() != 3 || fields.iter().any(|field| field.is_empty()) {
            manifest.malformed += 1;
            continue;
        }
        if manifest.rows.len() >= MAX_MANIFEST_ROWS {
            manifest.truncated = true;
            continue;
        }
        manifest.rows.push(PackageRow {
            name: fields[0].to_string(),
            version: fields[1].to_string(),
            architecture: fields[2].to_string(),
        });
    }
    manifest
}

/// Parse `os-release`: `KEY=value` lines, values optionally double- or
/// single-quoted, comments and blank lines skipped. No escape processing
/// beyond stripping the quotes, which is all the fields this surface reports
/// ever need.
#[must_use]
pub fn parse_os_release(text: &str) -> BTreeMap<String, String> {
    let mut fields = BTreeMap::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let value = value.trim();
        let value = value
            .strip_prefix('"')
            .and_then(|rest| rest.strip_suffix('"'))
            .or_else(|| {
                value
                    .strip_prefix('\'')
                    .and_then(|rest| rest.strip_suffix('\''))
            })
            .unwrap_or(value);
        fields.insert(key.trim().to_string(), value.to_string());
    }
    fields
}

/// Whether `text` is a machine id in the form systemd writes: 32 lowercase
/// hex characters.
#[must_use]
pub fn is_machine_id(text: &str) -> bool {
    text.len() == 32
        && text
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

/// Where the board model was read from.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Board {
    /// The model string, trimmed of the device tree's trailing NUL.
    pub model: String,
    /// `devicetree` or `dmi`.
    pub source: &'static str,
}

/// The grade of the signing material this image was built from.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TrustGrade {
    /// The marker is baked: the CA in this image's keyring, or the package
    /// signing key it trusts, or both, came out of a generator rather than a
    /// ceremony. `domains` is what the marker's `DOMAINS=` line names, so a
    /// mixed image says WHICH half.
    Development { domains: Vec<String> },
    /// The baked set is there and carries no marker: material an operator
    /// placed on purpose.
    Production,
}

/// Everything the observer reads. Each field is what one soft read produced;
/// absent means the read did not answer.
#[derive(Debug, Clone)]
pub struct SystemInfoEvidence {
    /// A well-formed machine id, or the reason there is none.
    pub machine_id: Result<String, String>,
    /// The board model, when the firmware exports one.
    pub board: Option<Board>,
    /// `uname -r`.
    pub kernel_release: Option<String>,
    /// `uname -v`.
    pub kernel_version: Option<String>,
    /// The parsed `os-release`, empty when the file is absent.
    pub os_release: BTreeMap<String, String>,
    /// The parsed manifest, or `None` when the file is absent.
    pub manifest: Option<Manifest>,
    /// The manifest file's mtime in seconds since the epoch: the pinned
    /// `SOURCE_DATE_EPOCH` every file in the image carries, not a build date.
    pub file_epoch: Option<u64>,
    /// Whole seconds since boot.
    pub uptime_seconds: Option<u64>,
    /// The grade of this image's signing material, or `None` when the baked
    /// `meta/` tree is not there to be asked. **`None` is not `Production`**:
    /// an image that provisions no anchor has no marker for the same reason a
    /// production image has none, and reporting the two the same way would
    /// have a device claiming a production CA it cannot see.
    pub trust: Option<TrustGrade>,
}

impl Default for SystemInfoEvidence {
    /// Nothing read yet: the machine id is absent with a reason, everything
    /// else is absent.
    fn default() -> Self {
        Self {
            machine_id: Err("not read".to_string()),
            board: None,
            kernel_release: None,
            kernel_version: None,
            os_release: BTreeMap::new(),
            manifest: None,
            file_epoch: None,
            uptime_seconds: None,
            trust: None,
        }
    }
}

/// This daemon's own identity, as its build embedded it — the values
/// `micad --version` prints, read from the same place.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DaemonIdentity {
    /// The daemon's name, `micad`: the executable, not the package.
    pub name: &'static str,
    /// The package version, `MICA_PACKAGE_VERSION`, or `unknown` for an
    /// unpackaged build.
    pub version: &'static str,
}

impl DaemonIdentity {
    /// The identity of this build.
    #[must_use]
    pub fn this_build() -> Self {
        Self {
            name: "micad",
            version: option_env!("MICA_PACKAGE_VERSION")
                .filter(|version| !version.trim().is_empty())
                .unwrap_or("unknown"),
        }
    }
}

/// Read-only source of system-information evidence.
#[async_trait::async_trait]
pub trait SystemInfoSource: Send + Sync {
    /// Observe the current evidence.
    ///
    /// # Errors
    ///
    /// Returns an error only when this daemon has no observer at all; a
    /// production observer answers with absent evidence instead.
    async fn observe(&self) -> Result<SystemInfoEvidence>;
}

/// The observer a daemon without host access has: none.
pub struct UnavailableSystemInfo;

#[async_trait::async_trait]
impl SystemInfoSource for UnavailableSystemInfo {
    async fn observe(&self) -> Result<SystemInfoEvidence> {
        Err(anyhow::anyhow!(
            "this daemon observes no system information"
        ))
    }
}

/// Production observer over a filesystem root.
///
/// `root` is a path prefix rather than a hard-coded `/` so the whole read can
/// be driven over a fixture tree in a unit test; production is the same thing
/// rooted at `/`.
pub struct HostSystemInfo {
    root: PathBuf,
}

impl HostSystemInfo {
    /// The observer `main.rs` attaches on a device.
    #[must_use]
    pub fn production() -> Self {
        Self::at("/")
    }

    /// An observer rooted at `root`.
    #[must_use]
    pub fn at(root: impl Into<PathBuf>) -> Self {
        Self { root: root.into() }
    }

    fn path(&self, relative: &str) -> PathBuf {
        self.root.join(relative)
    }

    fn read_trimmed(&self, relative: &str) -> Option<String> {
        // The device tree's model string is NUL-terminated; everything else
        // is a text file with a trailing newline.
        mica_fs::read_trimmed(&self.path(relative))
    }

    fn machine_id(&self) -> Result<String, String> {
        let path = self.path(MACHINE_ID_PATH);
        match std::fs::read_to_string(&path) {
            Ok(text) => {
                let text = text.trim();
                if is_machine_id(text) {
                    Ok(text.to_string())
                } else {
                    Err(format!(
                        "/{MACHINE_ID_PATH} is not a 32-character lowercase hex machine id"
                    ))
                }
            }
            Err(err) => Err(format!("/{MACHINE_ID_PATH} is not readable: {err}")),
        }
    }

    fn board(&self) -> Option<Board> {
        if let Some(model) = self.read_trimmed(DT_MODEL_PATH) {
            return Some(Board {
                model,
                source: "devicetree",
            });
        }
        let product = self.read_trimmed(DMI_PRODUCT_PATH)?;
        let model = match self.read_trimmed(DMI_VENDOR_PATH) {
            Some(vendor) => format!("{vendor} {product}"),
            None => product,
        };
        Some(Board {
            model,
            source: "dmi",
        })
    }

    fn manifest(&self) -> (Option<Manifest>, Option<u64>) {
        let path = self.path(MANIFEST_PATH);
        let Ok(text) = std::fs::read_to_string(&path) else {
            return (None, None);
        };
        let epoch = std::fs::metadata(&path)
            .and_then(|meta| meta.modified())
            .ok()
            .and_then(|modified| modified.duration_since(UNIX_EPOCH).ok())
            .map(|since| since.as_secs());
        let mut manifest = parse_manifest(&text);
        // The core components beside the root's packages, within the same cap.
        if let Ok(envelope) = std::fs::read_to_string(self.path(RUNNING_DEPLOYMENT_PATH)) {
            for row in core_rows(&envelope) {
                if manifest.rows.len() >= MAX_MANIFEST_ROWS {
                    manifest.truncated = true;
                    break;
                }
                manifest.rows.push(row);
            }
        }
        (Some(manifest), epoch)
    }

    /// The grade of the signing material this image was built from.
    fn trust(&self) -> Option<TrustGrade> {
        if !self.path(BAKED_META_MANIFEST_PATH).is_file() {
            return None;
        }
        let marker = self.path(BAKED_META_MARKER_PATH);
        if !marker.exists() {
            return Some(TrustGrade::Production);
        }
        // Present and unreadable still reports Development, with no domains.
        // The marker's presence is the claim; its contents only say which
        // half, and a read that failed must not promote the image to
        // production for want of a domain list.
        let text = std::fs::read_to_string(&marker).unwrap_or_default();
        Some(TrustGrade::Development {
            domains: marker_domains(&text),
        })
    }

    fn uptime_seconds(&self) -> Option<u64> {
        let contents = std::fs::read_to_string(self.path(UPTIME_PATH)).ok()?;
        let secs: f64 = contents.split_whitespace().next()?.parse().ok()?;
        (secs.is_finite() && secs >= 0.0).then_some(secs as u64)
    }
}

#[async_trait::async_trait]
impl SystemInfoSource for HostSystemInfo {
    async fn observe(&self) -> Result<SystemInfoEvidence> {
        let (manifest, file_epoch) = self.manifest();
        Ok(SystemInfoEvidence {
            machine_id: self.machine_id(),
            board: self.board(),
            kernel_release: self.read_trimmed(KERNEL_RELEASE_PATH),
            kernel_version: self.read_trimmed(KERNEL_VERSION_PATH),
            os_release: std::fs::read_to_string(self.path(OS_RELEASE_PATH))
                .map(|text| parse_os_release(&text))
                .unwrap_or_default(),
            manifest,
            file_epoch,
            uptime_seconds: self.uptime_seconds(),
            trust: self.trust(),
        })
    }
}

#[cfg(test)]
mod tests;
