//! Services appearing, vanishing and conforming.

use super::*;

/// 1. A conforming service appears with its direct-name class and an empty
///    conformance object.
#[tokio::test(flavor = "multi_thread")]
pub(super) async fn a_conforming_service_appears_with_no_conformance_gaps() {
    let harness = Harness::start().await;
    let name = "com.mica.sensor.fake";
    let _fake = harness.fake(name, conforming(3)).await;

    let services = harness.wait_for(name, |services| has(services, name)).await;
    let entry = entry(&services, name);

    assert_eq!(entry["name"], name);
    assert_eq!(
        entry["class"], "sensor",
        "the class of com.mica.sensor.fake is `sensor`; got {entry:#}"
    );
    assert_eq!(entry["connected"], true, "{entry:#}");
    assert_eq!(entry["instance"], 3, "{entry:#}");
    assert_eq!(
        entry["conformance"],
        serde_json::json!({}),
        "a service publishing all seven mandatory paths has no conformance gaps; got {entry:#}"
    );
    assert_eq!(entry["instance_collision"], false, "{entry:#}");

    // The WHOLE entry, field for field. Exact equality is the assertion that
    // the registry publishes the enumerated fields and NOTHING else: the fake
    // above answers `GetItems` with items of its own, and a registry that
    // dumped what a third-party service publishes would put whatever a service
    // chose to put in its items — secrets included — onto the bus and into the
    // logs. An extra key here fails this test.
    assert_eq!(
        entry,
        &serde_json::json!({
            "name": "com.mica.sensor.fake",
            "class": "sensor",
            "connected": true,
            "instance": 3,
            "conformance": {},
            "instance_collision": false,
        }),
        "the published entry must carry exactly the enumerated fields"
    );

    // micad keeps its own name out of the registry: the registry is its view of
    // the other services on the bus.
    assert!(
        !has(&services, "com.mica.micad"),
        "micad must not register itself; got {services:#}"
    );
}

/// 2. A vanished service is retained as disconnected; `ForgetService` drops it,
///    and refuses to drop one that is still connected.
#[tokio::test(flavor = "multi_thread")]
pub(super) async fn a_vanished_service_is_retained_and_only_then_forgettable() {
    let harness = Harness::start().await;
    let name = "com.mica.sensor.fake";
    let fake = harness.fake(name, conforming(1)).await;
    harness.wait_for(name, |services| has(services, name)).await;

    // The MEMBER NAME on the real interface, read back out of the daemon
    // rather than trusted: zbus renames a snake_case method to PascalCase, and
    // a client that guesses wrong gets UnknownMethod rather than a compile
    // error — including the client below, which is generated by the same
    // rename and so cannot detect a mismatch on its own.
    let introspectable = zbus::fdo::IntrospectableProxy::builder(&harness.connection)
        .destination("com.mica.micad")
        .expect("destination")
        .path("/com/mica/micad")
        .expect("path")
        .build()
        .await
        .expect("introspectable proxy");
    let xml = introspectable.introspect().await.expect("introspect");
    let opening = "<method name=\"ForgetService\">";
    let start = xml
        .find(opening)
        .unwrap_or_else(|| panic!("no ForgetService on com.mica.micad1:\n{xml}"));
    let body = &xml[start + opening.len()..];
    let body = &body[..body
        .find("</method>")
        .expect("the method element must close")];
    assert_eq!(
        body.matches("<arg").count(),
        1,
        "ForgetService takes exactly one argument, got:\n{body}"
    );
    assert!(
        body.contains("type=\"s\"") && body.contains("direction=\"in\""),
        "its one argument must be an `in` string — the bus name to forget, got:\n{body}"
    );

    // Connected: the removal is refused, and says why.
    let proxy = harness.proxy().await;
    let refused = proxy
        .forget_service(name)
        .await
        .expect_err("a connected service must not be forgettable");
    assert!(
        refused.to_string().contains("still connected"),
        "the refusal must name its reason: {refused}"
    );
    assert!(
        has(&harness.services().await, name),
        "a refused ForgetService must change nothing"
    );

    fake.vanish().await;

    // Retained, not evicted: an operator has to be able to see that a service
    // they installed has stopped appearing.
    let services = harness
        .wait_for("the entry to go disconnected", |services| {
            services.get(name).is_some_and(|e| e["connected"] == false)
        })
        .await;
    let entry = entry(&services, name);
    assert_eq!(entry["class"], "sensor", "{entry:#}");
    assert_eq!(entry["instance"], 1, "the cached facts survive: {entry:#}");

    // Disconnected: the removal is accepted, and the entry is gone.
    proxy
        .forget_service(name)
        .await
        .expect("a disconnected service can be forgotten");
    let services = harness.services().await;
    assert!(
        !has(&services, name),
        "ForgetService must drop the entry; got {services:#}"
    );
    assert!(
        proxy.forget_service(name).await.is_err(),
        "forgetting what is already gone is an error, not a silent success"
    );
}

/// 3. A service that answers no `com.mica.Item1` is still registered — warned
///    about, never refused. Both shapes of "no Item1" are here: the service
///    that refuses the call, and the one that never answers it.
#[tokio::test(flavor = "multi_thread")]
pub(super) async fn a_service_without_item1_is_registered_and_warned_about() {
    let harness = Harness::start().await;
    let silent = "com.mica.sensor.silent";
    let other = "com.mica.sensor.other";
    let _silent = harness.fake_that_answers_nothing(silent).await;
    let _other = harness.fake_with_another_interface(other).await;

    let services = harness
        .wait_for("both non-conforming services", |services| {
            has(services, silent) && has(services, other)
        })
        .await;

    for name in [silent, other] {
        let entry = entry(&services, name);
        assert_eq!(
            entry["conformance"]["item1"], false,
            "a service answering no com.mica.Item1 must be published saying so — that fact IS \
             the registry entry, and an operator who cannot see it concludes the bridge is \
             broken; got {entry:#}"
        );
        assert_eq!(entry["connected"], true, "{entry:#}");
        assert_eq!(entry["class"], "sensor", "{entry:#}");
        assert_eq!(
            entry["instance"], 0,
            "no /DeviceInstance means the fallback instance: {entry:#}"
        );
        let missing = entry["conformance"]["missing_paths"]
            .as_array()
            .unwrap_or_else(|| panic!("missing_paths must be a list; got {entry:#}"));
        assert_eq!(
            missing.len(),
            MANDATORY_PATHS.len(),
            "a service that answers nothing publishes none of the seven: {entry:#}"
        );
    }

    // Warned about exactly once each, naming the service — and nothing was
    // refused: the entries above are the proof of that.
    let log = harness
        .wait_for_log(&[silent, other, "does not conform"])
        .await;
    for name in [silent, other] {
        let warnings = log
            .lines()
            .filter(|line| line.contains("does not conform") && line.contains(name))
            .count();
        assert_eq!(
            warnings, 1,
            "exactly one warning per non-conforming service, got {warnings} for {name} in:\n{log}"
        );
    }
}
